#define LOAD_IMAGE_FAILED_STR		_T("Failed to load image")
#define SAVE_IMAGE_FAILED_STR		_T("Failed save image")
#define SAVE_IMAGE_NOT_READY_STR	_T("Failed save image, the image is not ready")
#define FILE_FILTER_STR				_T("JPG Files(*.jpg;*.jpeg)|*jpg;*jpeg|Bitmap Files(*.bmp)|*.bmp|All Files(*.*)|*.*||")
#define DEFAULT_SAVE_EXT_STR		_T("jpg")