#define LOAD_IMAGE_FAILED_STR		_T("Failed to load image")
#define SAVE_IMAGE_FAILED_STR		_T("Failed save image")
#define SAVE_IMAGE_NOT_READY_STR	_T("Failed save image, the image is not ready")
#define SET_PARAM_FAILED_STR		_T("Failed to set parameters")
#define FILE_FILTER_STR				_T("JPG文件(*.jpg;*.jpeg)|*jpg;*jpeg|位图文件(*.bmp)|*.bmp|所有文件(*.*)|*.*||")
#define DEFAULT_SAVE_EXT_STR		_T("jpg")